//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LinqStudio.Core.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "18.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class SharedResource {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal SharedResource() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("LinqStudio.Core.Resources.SharedResource", typeof(SharedResource).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Settings.
        /// </summary>
        public static string AppBar_Button_Settings {
            get {
                return ResourceManager.GetString("AppBar.Button.Settings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Technical Details.
        /// </summary>
        public static string ErrorDialog_Text_TechnicalDetails {
            get {
                return ResourceManager.GetString("ErrorDialog.Text.TechnicalDetails", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error.
        /// </summary>
        public static string ErrorDialog_Title_Error {
            get {
                return ResourceManager.GetString("ErrorDialog.Title.Error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No.
        /// </summary>
        public static string Global_MessageBox_No {
            get {
                return ResourceManager.GetString("Global.MessageBox.No", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Yes.
        /// </summary>
        public static string Global_MessageBox_Yes {
            get {
                return ResourceManager.GetString("Global.MessageBox.Yes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save all.
        /// </summary>
        public static string SettingsPage_Button_SaveAll {
            get {
                return ResourceManager.GetString("SettingsPage.Button.SaveAll", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error parsing setting JSON.
        /// </summary>
        public static string SettingsPage_Error_ErrorParsingSetting {
            get {
                return ResourceManager.GetString("SettingsPage.Error.ErrorParsingSetting", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error parsing setting JSON for {0}.
        /// </summary>
        public static string SettingsPage_Error_ErrorParsingSettingX {
            get {
                return ResourceManager.GetString("SettingsPage.Error.ErrorParsingSettingX", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error saving settings.
        /// </summary>
        public static string SettingsPage_Error_ErrorSavingSetting {
            get {
                return ResourceManager.GetString("SettingsPage.Error.ErrorSavingSetting", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Always.
        /// </summary>
        public static string SettingsPage_MessageBox_Always {
            get {
                return ResourceManager.GetString("SettingsPage.MessageBox.Always", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Settings have changed outside the editor, do you want to reload?.
        /// </summary>
        public static string SettingsPage_MessageBox_ReloadSettings {
            get {
                return ResourceManager.GetString("SettingsPage.MessageBox.ReloadSettings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reload settings?.
        /// </summary>
        public static string SettingsPage_MessageBox_ReloadTitle {
            get {
                return ResourceManager.GetString("SettingsPage.MessageBox.ReloadTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to UI Settings.
        /// </summary>
        public static string UserSettings_UISettings {
            get {
                return ResourceManager.GetString("UserSettings.UISettings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Automatically reload the UI in the settings page when the settings are changed from outside.
        /// </summary>
        public static string UserSettings_UISettings_AlwaysReloadSettingsInSettingsPage {
            get {
                return ResourceManager.GetString("UserSettings.UISettings.AlwaysReloadSettingsInSettingsPage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to True to set the UI in dark mode.
        /// </summary>
        public static string UserSettings_UISettings_IsDarkMode {
            get {
                return ResourceManager.GetString("UserSettings.UISettings.IsDarkMode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Connection Settings.
        /// </summary>
        public static string ConnectionSettings_Title {
            get {
                return ResourceManager.GetString("ConnectionSettings.Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Database Type.
        /// </summary>
        public static string ConnectionSettings_DatabaseType {
            get {
                return ResourceManager.GetString("ConnectionSettings.DatabaseType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Connection String.
        /// </summary>
        public static string ConnectionSettings_ConnectionString {
            get {
                return ResourceManager.GetString("ConnectionSettings.ConnectionString", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Validate Connection.
        /// </summary>
        public static string ConnectionSettings_Button_Validate {
            get {
                return ResourceManager.GetString("ConnectionSettings.Button.Validate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save.
        /// </summary>
        public static string ConnectionSettings_Button_Save {
            get {
                return ResourceManager.GetString("ConnectionSettings.Button.Save", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Close.
        /// </summary>
        public static string ConnectionSettings_Button_Close {
            get {
                return ResourceManager.GetString("ConnectionSettings.Button.Close", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You have unsaved changes. Are you sure you want to close?.
        /// </summary>
        public static string ConnectionSettings_Message_UnsavedChanges {
            get {
                return ResourceManager.GetString("ConnectionSettings.Message.UnsavedChanges", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unsaved Changes.
        /// </summary>
        public static string ConnectionSettings_Message_UnsavedChangesTitle {
            get {
                return ResourceManager.GetString("ConnectionSettings.Message.UnsavedChangesTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Connection validated successfully!.
        /// </summary>
        public static string ConnectionSettings_Message_ValidationSuccess {
            get {
                return ResourceManager.GetString("ConnectionSettings.Message.ValidationSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed to validate connection.
        /// </summary>
        public static string ConnectionSettings_Message_ValidationFailed {
            get {
                return ResourceManager.GetString("ConnectionSettings.Message.ValidationFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Connection settings saved successfully.
        /// </summary>
        public static string ConnectionSettings_Message_Saved {
            get {
                return ResourceManager.GetString("ConnectionSettings.Message.Saved", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Timeout.
        /// </summary>
        public static string ConnectionSettings_Timeout {
            get {
                return ResourceManager.GetString("ConnectionSettings.Timeout", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Testing connection....
        /// </summary>
        public static string ConnectionSettings_Message_Testing {
            get {
                return ResourceManager.GetString("ConnectionSettings.Message.Testing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Connection.
        /// </summary>
        public static string NavMenu_ConnectionSettings {
            get {
                return ResourceManager.GetString("NavMenu.ConnectionSettings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add Connection.
        /// </summary>
        public static string ObjectExplorer_Button_AddConnection {
            get {
                return ResourceManager.GetString("ObjectExplorer.Button.AddConnection", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Refresh All.
        /// </summary>
        public static string ObjectExplorer_Button_RefreshAll {
            get {
                return ResourceManager.GetString("ObjectExplorer.Button.RefreshAll", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Object Explorer.
        /// </summary>
        public static string ObjectExplorer_Title {
            get {
                return ResourceManager.GetString("ObjectExplorer.Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tables.
        /// </summary>
        public static string ObjectExplorer_Label_Tables {
            get {
                return ResourceManager.GetString("ObjectExplorer.Label.Tables", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Columns.
        /// </summary>
        public static string ObjectExplorer_Label_Columns {
            get {
                return ResourceManager.GetString("ObjectExplorer.Label.Columns", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Indexes.
        /// </summary>
        public static string ObjectExplorer_Label_Indexes {
            get {
                return ResourceManager.GetString("ObjectExplorer.Label.Indexes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Foreign Keys.
        /// </summary>
        public static string ObjectExplorer_Label_ForeignKeys {
            get {
                return ResourceManager.GetString("ObjectExplorer.Label.ForeignKeys", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Loading....
        /// </summary>
        public static string ObjectExplorer_Message_Loading {
            get {
                return ResourceManager.GetString("ObjectExplorer.Message.Loading", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No connections. Click "Add Connection" to get started..
        /// </summary>
        public static string ObjectExplorer_Message_NoConnections {
            get {
                return ResourceManager.GetString("ObjectExplorer.Message.NoConnections", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed to load database information.
        /// </summary>
        public static string ObjectExplorer_Message_Error {
            get {
                return ResourceManager.GetString("ObjectExplorer.Message.Error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Remove Connection.
        /// </summary>
        public static string ObjectExplorer_Button_RemoveConnection {
            get {
                return ResourceManager.GetString("ObjectExplorer.Button.RemoveConnection", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Refresh Connection.
        /// </summary>
        public static string ObjectExplorer_Button_RefreshConnection {
            get {
                return ResourceManager.GetString("ObjectExplorer.Button.RefreshConnection", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Connection Name.
        /// </summary>
        public static string ObjectExplorer_Dialog_ConnectionName {
            get {
                return ResourceManager.GetString("ObjectExplorer.Dialog.ConnectionName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter a name for this connection.
        /// </summary>
        public static string ObjectExplorer_Dialog_ConnectionNamePlaceholder {
            get {
                return ResourceManager.GetString("ObjectExplorer.Dialog.ConnectionNamePlaceholder", resourceCulture);
            }
        }
    }
}
