//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LinqStudio.Core.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "18.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class SharedResource {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal SharedResource() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("LinqStudio.Core.Resources.SharedResource", typeof(SharedResource).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Settings.
        /// </summary>
        public static string AppBar_Button_Settings {
            get {
                return ResourceManager.GetString("AppBar.Button.Settings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Close.
        /// </summary>
        public static string ConnectionSettings_Button_Close {
            get {
                return ResourceManager.GetString("ConnectionSettings.Button.Close", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save.
        /// </summary>
        public static string ConnectionSettings_Button_Save {
            get {
                return ResourceManager.GetString("ConnectionSettings.Button.Save", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Validate Connection.
        /// </summary>
        public static string ConnectionSettings_Button_Validate {
            get {
                return ResourceManager.GetString("ConnectionSettings.Button.Validate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Connection String.
        /// </summary>
        public static string ConnectionSettings_ConnectionString {
            get {
                return ResourceManager.GetString("ConnectionSettings.ConnectionString", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Database Type.
        /// </summary>
        public static string ConnectionSettings_DatabaseType {
            get {
                return ResourceManager.GetString("ConnectionSettings.DatabaseType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Connection settings saved successfully.
        /// </summary>
        public static string ConnectionSettings_Message_Saved {
            get {
                return ResourceManager.GetString("ConnectionSettings.Message.Saved", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Testing connection....
        /// </summary>
        public static string ConnectionSettings_Message_Testing {
            get {
                return ResourceManager.GetString("ConnectionSettings.Message.Testing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You have unsaved changes. Are you sure you want to close?.
        /// </summary>
        public static string ConnectionSettings_Message_UnsavedChanges {
            get {
                return ResourceManager.GetString("ConnectionSettings.Message.UnsavedChanges", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unsaved Changes.
        /// </summary>
        public static string ConnectionSettings_Message_UnsavedChangesTitle {
            get {
                return ResourceManager.GetString("ConnectionSettings.Message.UnsavedChangesTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed to validate connection.
        /// </summary>
        public static string ConnectionSettings_Message_ValidationFailed {
            get {
                return ResourceManager.GetString("ConnectionSettings.Message.ValidationFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Connection validated successfully!.
        /// </summary>
        public static string ConnectionSettings_Message_ValidationSuccess {
            get {
                return ResourceManager.GetString("ConnectionSettings.Message.ValidationSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Timeout.
        /// </summary>
        public static string ConnectionSettings_Timeout {
            get {
                return ResourceManager.GetString("ConnectionSettings.Timeout", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Connection Settings.
        /// </summary>
        public static string ConnectionSettings_Title {
            get {
                return ResourceManager.GetString("ConnectionSettings.Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cancel.
        /// </summary>
        public static string CustomRelationships_Button_Cancel {
            get {
                return ResourceManager.GetString("CustomRelationships.Button.Cancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save.
        /// </summary>
        public static string CustomRelationships_Button_Save {
            get {
                return ResourceManager.GetString("CustomRelationships.Button.Save", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Configure relationships.
        /// </summary>
        public static string CustomRelationships_ContextMenu {
            get {
                return ResourceManager.GetString("CustomRelationships.ContextMenu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Final version preview.
        /// </summary>
        public static string CustomRelationships_DbContext_FinalVersion {
            get {
                return ResourceManager.GetString("CustomRelationships.DbContext.FinalVersion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add code that will be placed in OnModelCreating. The preview shows the current final version..
        /// </summary>
        public static string CustomRelationships_DbContext_Help {
            get {
                return ResourceManager.GetString("CustomRelationships.DbContext.Help", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Manual configuration code.
        /// </summary>
        public static string CustomRelationships_DbContext_ManualCode {
            get {
                return ResourceManager.GetString("CustomRelationships.DbContext.ManualCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed to generate code preview..
        /// </summary>
        public static string CustomRelationships_Error_GenerateCode {
            get {
                return ResourceManager.GetString("CustomRelationships.Error.GenerateCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed to load database models..
        /// </summary>
        public static string CustomRelationships_Error_LoadModels {
            get {
                return ResourceManager.GetString("CustomRelationships.Error.LoadModels", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add key pair.
        /// </summary>
        public static string CustomRelationships_Form_AddKeyPair {
            get {
                return ResourceManager.GetString("CustomRelationships.Form.AddKeyPair", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cardinality.
        /// </summary>
        public static string CustomRelationships_Form_Cardinality {
            get {
                return ResourceManager.GetString("CustomRelationships.Form.Cardinality", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Many-to-many.
        /// </summary>
        public static string CustomRelationships_Form_Cardinality_ManyToMany {
            get {
                return ResourceManager.GetString("CustomRelationships.Form.Cardinality.ManyToMany", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Many {0} can be linked to many {1}..
        /// </summary>
        public static string CustomRelationships_Form_Cardinality_ManyToManyTooltip {
            get {
                return ResourceManager.GetString("CustomRelationships.Form.Cardinality.ManyToManyTooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Many-to-one.
        /// </summary>
        public static string CustomRelationships_Form_Cardinality_ManyToOne {
            get {
                return ResourceManager.GetString("CustomRelationships.Form.Cardinality.ManyToOne", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Many {1} can be linked to one {0}..
        /// </summary>
        public static string CustomRelationships_Form_Cardinality_ManyToOneTooltip {
            get {
                return ResourceManager.GetString("CustomRelationships.Form.Cardinality.ManyToOneTooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to One-to-many.
        /// </summary>
        public static string CustomRelationships_Form_Cardinality_OneToMany {
            get {
                return ResourceManager.GetString("CustomRelationships.Form.Cardinality.OneToMany", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to One {1} can be linked to many {0}..
        /// </summary>
        public static string CustomRelationships_Form_Cardinality_OneToManyTooltip {
            get {
                return ResourceManager.GetString("CustomRelationships.Form.Cardinality.OneToManyTooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to One-to-one.
        /// </summary>
        public static string CustomRelationships_Form_Cardinality_OneToOne {
            get {
                return ResourceManager.GetString("CustomRelationships.Form.Cardinality.OneToOne", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to One {0} is linked to one {1}..
        /// </summary>
        public static string CustomRelationships_Form_Cardinality_OneToOneTooltip {
            get {
                return ResourceManager.GetString("CustomRelationships.Form.Cardinality.OneToOneTooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete behavior.
        /// </summary>
        public static string CustomRelationships_Form_DeleteBehavior {
            get {
                return ResourceManager.GetString("CustomRelationships.Form.DeleteBehavior", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cascade.
        /// </summary>
        public static string CustomRelationships_Form_DeleteBehavior_Cascade {
            get {
                return ResourceManager.GetString("CustomRelationships.Form.DeleteBehavior.Cascade", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Client set null.
        /// </summary>
        public static string CustomRelationships_Form_DeleteBehavior_ClientSetNull {
            get {
                return ResourceManager.GetString("CustomRelationships.Form.DeleteBehavior.ClientSetNull", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No action.
        /// </summary>
        public static string CustomRelationships_Form_DeleteBehavior_NoAction {
            get {
                return ResourceManager.GetString("CustomRelationships.Form.DeleteBehavior.NoAction", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Restrict.
        /// </summary>
        public static string CustomRelationships_Form_DeleteBehavior_Restrict {
            get {
                return ResourceManager.GetString("CustomRelationships.Form.DeleteBehavior.Restrict", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Choose what happens to linked rows when the principal table row is deleted..
        /// </summary>
        public static string CustomRelationships_Form_DeleteBehaviorTooltip {
            get {
                return ResourceManager.GetString("CustomRelationships.Form.DeleteBehaviorTooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dependent column.
        /// </summary>
        public static string CustomRelationships_Form_DependentColumn {
            get {
                return ResourceManager.GetString("CustomRelationships.Form.DependentColumn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dependent navigation property.
        /// </summary>
        public static string CustomRelationships_Form_DependentNavigation {
            get {
                return ResourceManager.GetString("CustomRelationships.Form.DependentNavigation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The property {1} will be added to the {0} class: {2} {1} {{ get; set; }}.
        /// </summary>
        public static string CustomRelationships_Form_DependentNavigationTooltip {
            get {
                return ResourceManager.GetString("CustomRelationships.Form.DependentNavigationTooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Key pairs.
        /// </summary>
        public static string CustomRelationships_Form_KeyPairs {
            get {
                return ResourceManager.GetString("CustomRelationships.Form.KeyPairs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Link to table.
        /// </summary>
        public static string CustomRelationships_Form_LinkToTable {
            get {
                return ResourceManager.GetString("CustomRelationships.Form.LinkToTable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Choose the table that {0} should link to..
        /// </summary>
        public static string CustomRelationships_Form_LinkToTableTooltip {
            get {
                return ResourceManager.GetString("CustomRelationships.Form.LinkToTableTooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Matching key in {0}.
        /// </summary>
        public static string CustomRelationships_Form_MatchingKey {
            get {
                return ResourceManager.GetString("CustomRelationships.Form.MatchingKey", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pick the matching key column in {0}..
        /// </summary>
        public static string CustomRelationships_Form_MatchingKeyTooltip {
            get {
                return ResourceManager.GetString("CustomRelationships.Form.MatchingKeyTooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Navigation properties.
        /// </summary>
        public static string CustomRelationships_Form_Navigation {
            get {
                return ResourceManager.GetString("CustomRelationships.Form.Navigation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New relationship.
        /// </summary>
        public static string CustomRelationships_Form_New {
            get {
                return ResourceManager.GetString("CustomRelationships.Form.New", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Principal column.
        /// </summary>
        public static string CustomRelationships_Form_PrincipalColumn {
            get {
                return ResourceManager.GetString("CustomRelationships.Form.PrincipalColumn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Principal navigation property.
        /// </summary>
        public static string CustomRelationships_Form_PrincipalNavigation {
            get {
                return ResourceManager.GetString("CustomRelationships.Form.PrincipalNavigation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The property {1} will be added to the {0} class: {2} {1} {{ get; set; }}.
        /// </summary>
        public static string CustomRelationships_Form_PrincipalNavigationTooltip {
            get {
                return ResourceManager.GetString("CustomRelationships.Form.PrincipalNavigationTooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Principal table.
        /// </summary>
        public static string CustomRelationships_Form_PrincipalTable {
            get {
                return ResourceManager.GetString("CustomRelationships.Form.PrincipalTable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Each {0} must be linked to a {1}.
        /// </summary>
        public static string CustomRelationships_Form_Required {
            get {
                return ResourceManager.GetString("CustomRelationships.Form.Required", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Turn this on when every {0} must be linked to a {1}..
        /// </summary>
        public static string CustomRelationships_Form_RequiredTooltip {
            get {
                return ResourceManager.GetString("CustomRelationships.Form.RequiredTooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save relationship.
        /// </summary>
        public static string CustomRelationships_Form_Save {
            get {
                return ResourceManager.GetString("CustomRelationships.Form.Save", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Column in {0}.
        /// </summary>
        public static string CustomRelationships_Form_SelectedColumn {
            get {
                return ResourceManager.GetString("CustomRelationships.Form.SelectedColumn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pick the column in {0} that contains the link..
        /// </summary>
        public static string CustomRelationships_Form_SelectedColumnTooltip {
            get {
                return ResourceManager.GetString("CustomRelationships.Form.SelectedColumnTooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Generated code is unavailable until a database connection is configured..
        /// </summary>
        public static string CustomRelationships_GeneratedCode_Empty {
            get {
                return ResourceManager.GetString("CustomRelationships.GeneratedCode.Empty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Generated file.
        /// </summary>
        public static string CustomRelationships_GeneratedCode_File {
            get {
                return ResourceManager.GetString("CustomRelationships.GeneratedCode.File", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This is the source generated for IntelliSense and query compilation..
        /// </summary>
        public static string CustomRelationships_GeneratedCode_Help {
            get {
                return ResourceManager.GetString("CustomRelationships.GeneratedCode.Help", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Editing model.
        /// </summary>
        public static string CustomRelationships_Models_Editing {
            get {
                return ResourceManager.GetString("CustomRelationships.Models.Editing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Models.
        /// </summary>
        public static string CustomRelationships_Models_Models {
            get {
                return ResourceManager.GetString("CustomRelationships.Models.Models", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select a model to configure its relationships..
        /// </summary>
        public static string CustomRelationships_Models_SelectModel {
            get {
                return ResourceManager.GetString("CustomRelationships.Models.SelectModel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DbContext.
        /// </summary>
        public static string CustomRelationships_Tab_DbContext {
            get {
                return ResourceManager.GetString("CustomRelationships.Tab.DbContext", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Generated code.
        /// </summary>
        public static string CustomRelationships_Tab_GeneratedCode {
            get {
                return ResourceManager.GetString("CustomRelationships.Tab.GeneratedCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Models.
        /// </summary>
        public static string CustomRelationships_Tab_Models {
            get {
                return ResourceManager.GetString("CustomRelationships.Tab.Models", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Configure relationships.
        /// </summary>
        public static string CustomRelationships_Title {
            get {
                return ResourceManager.GetString("CustomRelationships.Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New Query.
        /// </summary>
        public static string DatabaseTreeView_ContextMenu_NewQuery {
            get {
                return ResourceManager.GetString("DatabaseTreeView.ContextMenu.NewQuery", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Refresh.
        /// </summary>
        public static string DatabaseTreeView_ContextMenu_Refresh {
            get {
                return ResourceManager.GetString("DatabaseTreeView.ContextMenu.Refresh", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select top 1000.
        /// </summary>
        public static string DatabaseTreeView_ContextMenu_SelectTop1000 {
            get {
                return ResourceManager.GetString("DatabaseTreeView.ContextMenu.SelectTop1000", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unable to load columns..
        /// </summary>
        public static string DatabaseTreeView_LoadColumnsError {
            get {
                return ResourceManager.GetString("DatabaseTreeView.LoadColumnsError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed to load table columns..
        /// </summary>
        public static string DatabaseTreeView_LoadColumnsErrorDialog {
            get {
                return ResourceManager.GetString("DatabaseTreeView.LoadColumnsErrorDialog", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unable to load tables..
        /// </summary>
        public static string DatabaseTreeView_LoadError {
            get {
                return ResourceManager.GetString("DatabaseTreeView.LoadError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed to load database tables..
        /// </summary>
        public static string DatabaseTreeView_LoadErrorDialog {
            get {
                return ResourceManager.GetString("DatabaseTreeView.LoadErrorDialog", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Loading columns....
        /// </summary>
        public static string DatabaseTreeView_LoadingColumns {
            get {
                return ResourceManager.GetString("DatabaseTreeView.LoadingColumns", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No tables match this filter..
        /// </summary>
        public static string DatabaseTreeView_NoMatches {
            get {
                return ResourceManager.GetString("DatabaseTreeView.NoMatches", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Open a project to explore database tables.
        /// </summary>
        public static string DatabaseTreeView_Placeholder {
            get {
                return ResourceManager.GetString("DatabaseTreeView.Placeholder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Refresh tables.
        /// </summary>
        public static string DatabaseTreeView_Refresh {
            get {
                return ResourceManager.GetString("DatabaseTreeView.Refresh", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Retry.
        /// </summary>
        public static string DatabaseTreeView_Retry {
            get {
                return ResourceManager.GetString("DatabaseTreeView.Retry", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Filter tables.
        /// </summary>
        public static string DatabaseTreeView_SearchLabel {
            get {
                return ResourceManager.GetString("DatabaseTreeView.SearchLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Search by table or schema.
        /// </summary>
        public static string DatabaseTreeView_SearchPlaceholder {
            get {
                return ResourceManager.GetString("DatabaseTreeView.SearchPlaceholder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tables.
        /// </summary>
        public static string DatabaseTreeView_Tables {
            get {
                return ResourceManager.GetString("DatabaseTreeView.Tables", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No project is open. Please create or open a project to start editing queries..
        /// </summary>
        public static string Editor_NoProjectAlert {
            get {
                return ResourceManager.GetString("Editor.NoProjectAlert", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No queries are currently open. Right-click the database connection in the explorer to create a new query..
        /// </summary>
        public static string Editor_NoQueryAlert {
            get {
                return ResourceManager.GetString("Editor.NoQueryAlert", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Editor - LinqStudio.
        /// </summary>
        public static string Editor_Title {
            get {
                return ResourceManager.GetString("Editor.Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Technical Details.
        /// </summary>
        public static string ErrorDialog_Text_TechnicalDetails {
            get {
                return ResourceManager.GetString("ErrorDialog.Text.TechnicalDetails", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error.
        /// </summary>
        public static string ErrorDialog_Title_Error {
            get {
                return ResourceManager.GetString("ErrorDialog.Title.Error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No.
        /// </summary>
        public static string Global_MessageBox_No {
            get {
                return ResourceManager.GetString("Global.MessageBox.No", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Yes.
        /// </summary>
        public static string Global_MessageBox_Yes {
            get {
                return ResourceManager.GetString("Global.MessageBox.Yes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Connection.
        /// </summary>
        public static string NavMenu_ConnectionSettings {
            get {
                return ResourceManager.GetString("NavMenu.ConnectionSettings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Close query.
        /// </summary>
        public static string QueryEditor_Button_Close {
            get {
                return ResourceManager.GetString("QueryEditor.Button.Close", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Execute.
        /// </summary>
        public static string QueryEditor_Button_Execute {
            get {
                return ResourceManager.GetString("QueryEditor.Button.Execute", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Refresh schema.
        /// </summary>
        public static string QueryEditor_Button_RefreshSchema {
            get {
                return ResourceManager.GetString("QueryEditor.Button.RefreshSchema", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save query.
        /// </summary>
        public static string QueryEditor_Button_Save {
            get {
                return ResourceManager.GetString("QueryEditor.Button.Save", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Stop.
        /// </summary>
        public static string QueryEditor_Button_Stop {
            get {
                return ResourceManager.GetString("QueryEditor.Button.Stop", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed to save edited row..
        /// </summary>
        public static string QueryEditor_Error_SaveEditedRow {
            get {
                return ResourceManager.GetString("QueryEditor.Error.SaveEditedRow", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed to update edited cell..
        /// </summary>
        public static string QueryEditor_Error_UpdateEditedCell {
            get {
                return ResourceManager.GetString("QueryEditor.Error.UpdateEditedCell", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Query execution cancelled..
        /// </summary>
        public static string QueryEditor_Message_Cancelled {
            get {
                return ResourceManager.GetString("QueryEditor.Message.Cancelled", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Editor not ready. Please try again..
        /// </summary>
        public static string QueryEditor_Message_EditorNotReady {
            get {
                return ResourceManager.GetString("QueryEditor.Message.EditorNotReady", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Query is empty..
        /// </summary>
        public static string QueryEditor_Message_Empty {
            get {
                return ResourceManager.GetString("QueryEditor.Message.Empty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Query completed successfully. {0} rows returned..
        /// </summary>
        public static string QueryEditor_Message_Executed {
            get {
                return ResourceManager.GetString("QueryEditor.Message.Executed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No project is open..
        /// </summary>
        public static string QueryEditor_Message_NoProject {
            get {
                return ResourceManager.GetString("QueryEditor.Message.NoProject", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Query saved successfully..
        /// </summary>
        public static string QueryEditor_Message_Saved {
            get {
                return ResourceManager.GetString("QueryEditor.Message.Saved", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save the project first before saving queries..
        /// </summary>
        public static string QueryEditor_Message_SaveProjectFirst {
            get {
                return ResourceManager.GetString("QueryEditor.Message.SaveProjectFirst", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This query has unsaved changes. Close without saving?.
        /// </summary>
        public static string QueryEditor_Message_UnsavedClose {
            get {
                return ResourceManager.GetString("QueryEditor.Message.UnsavedClose", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New Query.
        /// </summary>
        public static string QueryEditor_Query_New {
            get {
                return ResourceManager.GetString("QueryEditor.Query.New", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unsaved.
        /// </summary>
        public static string QueryEditor_Query_Unsaved {
            get {
                return ResourceManager.GetString("QueryEditor.Query.Unsaved", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to C# is not available for this query..
        /// </summary>
        public static string QueryEditor_Results_CSharpUnavailable {
            get {
                return ResourceManager.GetString("QueryEditor.Results.CSharpUnavailable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Run a query to see the generated C# code..
        /// </summary>
        public static string QueryEditor_Results_RunForCSharp {
            get {
                return ResourceManager.GetString("QueryEditor.Results.RunForCSharp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Run a query to see the generated SQL..
        /// </summary>
        public static string QueryEditor_Results_RunForSql {
            get {
                return ResourceManager.GetString("QueryEditor.Results.RunForSql", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SQL is not available for this query..
        /// </summary>
        public static string QueryEditor_Results_SqlUnavailable {
            get {
                return ResourceManager.GetString("QueryEditor.Results.SqlUnavailable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to C#.
        /// </summary>
        public static string QueryEditor_Results_TabCSharp {
            get {
                return ResourceManager.GetString("QueryEditor.Results.TabCSharp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Results.
        /// </summary>
        public static string QueryEditor_Results_TabResults {
            get {
                return ResourceManager.GetString("QueryEditor.Results.TabResults", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SQL.
        /// </summary>
        public static string QueryEditor_Results_TabSql {
            get {
                return ResourceManager.GetString("QueryEditor.Results.TabSql", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Query output.
        /// </summary>
        public static string QueryEditor_Results_Title {
            get {
                return ResourceManager.GetString("QueryEditor.Results.Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Completed.
        /// </summary>
        public static string QueryEditor_Status_Completed {
            get {
                return ResourceManager.GetString("QueryEditor.Status.Completed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Executing query....
        /// </summary>
        public static string QueryEditor_Status_Executing {
            get {
                return ResourceManager.GetString("QueryEditor.Status.Executing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed.
        /// </summary>
        public static string QueryEditor_Status_Failed {
            get {
                return ResourceManager.GetString("QueryEditor.Status.Failed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Not executed.
        /// </summary>
        public static string QueryEditor_Status_NotExecuted {
            get {
                return ResourceManager.GetString("QueryEditor.Status.NotExecuted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Refreshing....
        /// </summary>
        public static string QueryEditor_Status_Refreshing {
            get {
                return ResourceManager.GetString("QueryEditor.Status.Refreshing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Execution.
        /// </summary>
        public static string QueryEditor_Toolbar_Execution {
            get {
                return ResourceManager.GetString("QueryEditor.Toolbar.Execution", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No timeout.
        /// </summary>
        public static string QueryEditor_Toolbar_NoTimeout {
            get {
                return ResourceManager.GetString("QueryEditor.Toolbar.NoTimeout", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Timeout.
        /// </summary>
        public static string QueryEditor_Toolbar_Timeout {
            get {
                return ResourceManager.GetString("QueryEditor.Toolbar.Timeout", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Compilation error.
        /// </summary>
        public static string QueryResultGrid_CompilationError {
            get {
                return ResourceManager.GetString("QueryResultGrid.CompilationError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Elapsed.
        /// </summary>
        public static string QueryResultGrid_Elapsed {
            get {
                return ResourceManager.GetString("QueryResultGrid.Elapsed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Query returned no results..
        /// </summary>
        public static string QueryResultGrid_NoResults {
            get {
                return ResourceManager.GetString("QueryResultGrid.NoResults", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to row.
        /// </summary>
        public static string QueryResultGrid_Row {
            get {
                return ResourceManager.GetString("QueryResultGrid.Row", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} {1}.
        /// </summary>
        public static string QueryResultGrid_RowCount {
            get {
                return ResourceManager.GetString("QueryResultGrid.RowCount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to rows.
        /// </summary>
        public static string QueryResultGrid_Rows {
            get {
                return ResourceManager.GetString("QueryResultGrid.Rows", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to selected.
        /// </summary>
        public static string QueryResultGrid_Selected {
            get {
                return ResourceManager.GetString("QueryResultGrid.Selected", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save all.
        /// </summary>
        public static string SettingsPage_Button_SaveAll {
            get {
                return ResourceManager.GetString("SettingsPage.Button.SaveAll", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error parsing setting JSON.
        /// </summary>
        public static string SettingsPage_Error_ErrorParsingSetting {
            get {
                return ResourceManager.GetString("SettingsPage.Error.ErrorParsingSetting", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error parsing setting JSON for {0}.
        /// </summary>
        public static string SettingsPage_Error_ErrorParsingSettingX {
            get {
                return ResourceManager.GetString("SettingsPage.Error.ErrorParsingSettingX", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error saving settings.
        /// </summary>
        public static string SettingsPage_Error_ErrorSavingSetting {
            get {
                return ResourceManager.GetString("SettingsPage.Error.ErrorSavingSetting", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Always.
        /// </summary>
        public static string SettingsPage_MessageBox_Always {
            get {
                return ResourceManager.GetString("SettingsPage.MessageBox.Always", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Settings have changed outside the editor, do you want to reload?.
        /// </summary>
        public static string SettingsPage_MessageBox_ReloadSettings {
            get {
                return ResourceManager.GetString("SettingsPage.MessageBox.ReloadSettings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reload settings?.
        /// </summary>
        public static string SettingsPage_MessageBox_ReloadTitle {
            get {
                return ResourceManager.GetString("SettingsPage.MessageBox.ReloadTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Toggle theme.
        /// </summary>
        public static string Shell_Button_ToggleTheme {
            get {
                return ResourceManager.GetString("Shell.Button.ToggleTheme", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Connection.
        /// </summary>
        public static string Shell_Connection_Label {
            get {
                return ResourceManager.GetString("Shell.Connection.Label", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No project open.
        /// </summary>
        public static string Shell_Connection_None {
            get {
                return ResourceManager.GetString("Shell.Connection.None", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Database objects.
        /// </summary>
        public static string Shell_Explorer_Subtitle {
            get {
                return ResourceManager.GetString("Shell.Explorer.Subtitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Object Explorer.
        /// </summary>
        public static string Shell_Explorer_Title {
            get {
                return ResourceManager.GetString("Shell.Explorer.Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Navigation.
        /// </summary>
        public static string Shell_Navigation_Label {
            get {
                return ResourceManager.GetString("Shell.Navigation.Label", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Toggle navigation.
        /// </summary>
        public static string Shell_Navigation_Toggle {
            get {
                return ResourceManager.GetString("Shell.Navigation.Toggle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No project open.
        /// </summary>
        public static string Shell_Status_NoProject {
            get {
                return ResourceManager.GetString("Shell.Status.NoProject", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ready.
        /// </summary>
        public static string Shell_Status_Ready {
            get {
                return ResourceManager.GetString("Shell.Status.Ready", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unsaved changes.
        /// </summary>
        public static string Shell_Status_Unsaved {
            get {
                return ResourceManager.GetString("Shell.Status.Unsaved", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Query Execution.
        /// </summary>
        public static string UserSettings_QueryExecutionSettings {
            get {
                return ResourceManager.GetString("UserSettings.QueryExecutionSettings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Query Timeout (seconds).
        /// </summary>
        public static string UserSettings_QueryExecutionSettings_TimeoutSeconds {
            get {
                return ResourceManager.GetString("UserSettings.QueryExecutionSettings.TimeoutSeconds", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to UI Settings.
        /// </summary>
        public static string UserSettings_UISettings {
            get {
                return ResourceManager.GetString("UserSettings.UISettings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Automatically reload the UI in the settings page when the settings are changed from outside.
        /// </summary>
        public static string UserSettings_UISettings_AlwaysReloadSettingsInSettingsPage {
            get {
                return ResourceManager.GetString("UserSettings.UISettings.AlwaysReloadSettingsInSettingsPage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to True to set the UI in dark mode.
        /// </summary>
        public static string UserSettings_UISettings_IsDarkMode {
            get {
                return ResourceManager.GetString("UserSettings.UISettings.IsDarkMode", resourceCulture);
            }
        }
    }
}
