//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LinqStudio.Core.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "18.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class SharedResource {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal SharedResource() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("LinqStudio.Core.Resources.SharedResource", typeof(SharedResource).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Settings.
        /// </summary>
        public static string AppBar_Button_Settings {
            get {
                return ResourceManager.GetString("AppBar.Button.Settings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Technical Details.
        /// </summary>
        public static string ErrorDialog_Text_TechnicalDetails {
            get {
                return ResourceManager.GetString("ErrorDialog.Text.TechnicalDetails", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error.
        /// </summary>
        public static string ErrorDialog_Title_Error {
            get {
                return ResourceManager.GetString("ErrorDialog.Title.Error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No.
        /// </summary>
        public static string Global_MessageBox_No {
            get {
                return ResourceManager.GetString("Global.MessageBox.No", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Yes.
        /// </summary>
        public static string Global_MessageBox_Yes {
            get {
                return ResourceManager.GetString("Global.MessageBox.Yes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save all.
        /// </summary>
        public static string SettingsPage_Button_SaveAll {
            get {
                return ResourceManager.GetString("SettingsPage.Button.SaveAll", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error parsing setting JSON.
        /// </summary>
        public static string SettingsPage_Error_ErrorParsingSetting {
            get {
                return ResourceManager.GetString("SettingsPage.Error.ErrorParsingSetting", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error parsing setting JSON for {0}.
        /// </summary>
        public static string SettingsPage_Error_ErrorParsingSettingX {
            get {
                return ResourceManager.GetString("SettingsPage.Error.ErrorParsingSettingX", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error saving settings.
        /// </summary>
        public static string SettingsPage_Error_ErrorSavingSetting {
            get {
                return ResourceManager.GetString("SettingsPage.Error.ErrorSavingSetting", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Always.
        /// </summary>
        public static string SettingsPage_MessageBox_Always {
            get {
                return ResourceManager.GetString("SettingsPage.MessageBox.Always", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Settings have changed outside the editor, do you want to reload?.
        /// </summary>
        public static string SettingsPage_MessageBox_ReloadSettings {
            get {
                return ResourceManager.GetString("SettingsPage.MessageBox.ReloadSettings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reload settings?.
        /// </summary>
        public static string SettingsPage_MessageBox_ReloadTitle {
            get {
                return ResourceManager.GetString("SettingsPage.MessageBox.ReloadTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to UI Settings.
        /// </summary>
        public static string UserSettings_UISettings {
            get {
                return ResourceManager.GetString("UserSettings.UISettings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Automatically reload the UI in the settings page when the settings are changed from outside.
        /// </summary>
        public static string UserSettings_UISettings_AlwaysReloadSettingsInSettingsPage {
            get {
                return ResourceManager.GetString("UserSettings.UISettings.AlwaysReloadSettingsInSettingsPage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to True to set the UI in dark mode.
        /// </summary>
        public static string UserSettings_UISettings_IsDarkMode {
            get {
                return ResourceManager.GetString("UserSettings.UISettings.IsDarkMode", resourceCulture);
            }
        }
    }
}
